name: CI/CD pipeline
on:
  push:
    branches:
      - dev
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd app
          npm ci

      - name: Run tests
        run: |
          cd app
          npm run test

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh/ansible
          echo "${{ secrets.DEV_SSH_KEY }}" > ~/.ssh/ansible/id_rsa_dev
          echo "${{ secrets.PROD_SSH_KEY }}" > ~/.ssh/ansible/id_rsa_prod
          chmod 600 ~/.ssh/ansible/*

          mkdir -p ansible/keys
          cp ~/.ssh/ansible/id_rsa_dev ansible/keys/id_rsa_dev
          cp ~/.ssh/ansible/id_rsa_prod ansible/keys/id_rsa_prod

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install ansible

      - name: Deploy to Dev
        if: github.ref == 'refs/heads/dev'
        run: |
          ansible-playbook -i ansible/inventory/dev.ini ansible/playbooks/deploy-dev.yml

      - name: Deploy to Prod
        if: github.ref == 'refs/heads/main'
        run: |
          ansible-playbook -i ansible/inventory/prod.ini ansible/playbooks/deploy-prod.yml
